version: "3.8"
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    network_mode: service:devcontainer

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    network_mode: service:devcontainer
    

  redis:
    image: redis:alpine
    network_mode: service:devcontainer

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
  mongo-data:
