version: "3.8"

services:
  workspace:
    image: mcr.microsoft.com/devcontainers/base:debian
    volumes:
      - ..:/workspace:delegated
    command: sleep infinity
    environment:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres?schema=public

  postgres:
    image: postgres:13.6-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    network_mode: "service:workspace"

volumes:
  postgres-data:
